name: Build frontend

on:
  workflow_call:

jobs:
  deploy:
    runs-on: ubuntu-latest

    timeout-minutes: 2

    defaults:
      run:
        working-directory: ./frontend

    steps:
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Cache node_modules
        env:
          cache-name: cache-node-modules
        uses: actions/cache@v3
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/yarn.lock') }}

      - name: Install dependencies
        run: yarn install

      - name: ls
        run: ls -a

      - name: Build project
        run: yarn build
