name: Deploy all

on: [workflow_dispatch]

jobs:
  initalize:
    uses: ./.github/workflows/initialize.yml

  build-frontend:
    uses: ./.github/workflows/build-frontend.yml
    needs: initalize

  terraform:
    uses: ./.github/workflows/terraform-apply.yml
    needs: [initalize, build-frontend]
