name: Deploy Production

on: [workflow_dispatch]

jobs:
  build-frontend:
    name: Build Frontend
    runs-on: ubuntu-latest
    timeout-minutes: 5

    defaults:
      run:
        working-directory: frontend

    steps:
      - name: Clone repository
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Cache node_modules
        env:
          cache-name: cache-node-modules
        uses: actions/cache@v3
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/yarn.lock') }}

      - name: Build project
        run: |
          yarn install
          yarn build

      - name: Archive production artifacts
        uses: actions/upload-artifact@v3
        with:
          name: frontend
          retention-days: 1
          path: frontend/dist/
          if-no-files-found: error

  build-backend:
    name: Build Backend
    runs-on: ubuntu-latest
    timeout-minutes: 5

    defaults:
      run:
        working-directory: backend

    strategy:
      matrix:
        project:
          [
            ArticlesWeb.Functions.Comments.Get,
            ArticlesWeb.Functions.Comments.Create,
          ]

    steps:
      - name: Clone repository
        uses: actions/checkout@v2

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: "6.0.x"

      - name: Cache NuGet packages
        env:
          cache-name: cache-nuget-packages
        uses: actions/cache@v3
        with:
          path: "**/.nuget/packages"
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ matrix.project }}-${{ hashFiles('**/packages.lock.json') }}

      - name: Install dependencies
        run: dotnet restore ${{ matrix.project }}

      - name: Build project
        run: dotnet build ${{ matrix.project }} --configuration Release --no-restore --output build

      - name: Zip project
        shell: bash
        run: |
          cd build
          zip -r ../${{ matrix.project }}.zip *

      - name: Archive production artifacts
        uses: actions/upload-artifact@v3
        with:
          name: backend
          retention-days: 1
          path: backend/${{ matrix.project }}/build/${{ matrix.project }}.zip
          if-no-files-found: error

  plan:
    name: Plan Deployment
    needs: build-frontend
    runs-on: ubuntu-latest
    timeout-minutes: 10

    defaults:
      run:
        working-directory: infrastructure

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Clone repository
        uses: actions/checkout@v2

      - name: Download frontend artifacts
        uses: actions/download-artifact@v3
        with:
          name: frontend
          path: infrastructure/artifacts/frontend

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.1.9

      - name: Plan Terraform
        env:
          TF_VAR_allowed_account_id: ${{ secrets.ALLOWED_ACCOUNT_ID }}
        run: |
          terraform init -input=false
          terraform plan -input=false -no-color

  deploy:
    name: Deploy
    needs: plan
    runs-on: ubuntu-latest
    environment: Production
    timeout-minutes: 10

    defaults:
      run:
        working-directory: infrastructure

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Clone repository
        uses: actions/checkout@v2

      - name: Download frontend artifacts
        uses: actions/download-artifact@v3
        with:
          name: frontend
          path: infrastructure/artifacts/frontend

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.1.9

      - name: Apply Terraform
        env:
          TF_VAR_allowed_account_id: ${{ secrets.ALLOWED_ACCOUNT_ID }}
        run: |
          terraform init -input=false
          terraform apply -auto-approve -input=false

  post-deploy:
    name: Post-Deployment
    needs: deploy
    runs-on: ubuntu-latest

    timeout-minutes: 2

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Invalidate CloudFront
        run: aws cloudfront create-invalidation --distribution-id ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }} --paths '/*'
