name: Deploy

on: [workflow_dispatch]

jobs:
  build-frontend:
    name: Build Frontend
    runs-on: ubuntu-latest
    timeout-minutes: 3

    defaults:
      run:
        working-directory: ./frontend

    steps:
      - name: Clone repository
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Cache node_modules
        env:
          cache-name: cache-node-modules
        uses: actions/cache@v3
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/yarn.lock') }}

      - name: Build project
        run: |
          yarn install
          yarn build

      - name: ls
        run: ls -a

      - name: Archive production artifacts
        uses: actions/upload-artifact@v3
        with:
          name: frontend
          retention-days: 1
          path: ./dist

  plan-terraform:
    name: Plan Terraform
    needs: build-frontend
    runs-on: ubuntu-latest
    timeout-minutes: 10

    defaults:
      run:
        working-directory: ./infrastructure

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download frontend artifacts
        uses: actions/download-artifact@v3
        with:
          name: frontend

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.1.9

      - name: Plan Terraform
        env:
          TF_VAR_allowed_account_id: ${{ secrets.ALLOWED_ACCOUNT_ID }}
        run: |
          terraform init -input=false
          terraform validate -no-color
          terraform plan -input=false -no-color
