name: Deploy backend

on: [workflow_dispatch]

jobs:
  deploy:
    strategy:
      matrix:
        include:
          - project: ArticlesWeb.Functions.Comments.Get
            function-name: Articles_Comments_Get

          - project: ArticlesWeb.Functions.Comments.Create
            function-name: Articles_Comments_Create

    runs-on: ubuntu-latest

    env:
      DOTNET_NOLOGO: true

    permissions:
      id-token: write
      contents: read

    defaults:
      run:
        working-directory: ./backend/${{ matrix.project }}

    timeout-minutes: 10

    steps:
      - name: Clone repository
        uses: actions/checkout@v2

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: "6.0.x"

      - name: Cache NuGet packages
        env:
          cache-name: cache-nuget-packages
        uses: actions/cache@v3
        with:
          path: "**/.nuget/packages"
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ matrix.project }}-${{ hashFiles('**/packages.lock.json') }}

      - name: Install dependencies
        run: dotnet restore

      - name: Build project
        run: dotnet build --configuration Release --no-restore --output build

      - name: Zip project
        shell: bash
        run: |
          cd build
          zip -r ../${{ matrix.project }}.zip *

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Deploy lambda function
        run: aws lambda update-function-code --function-name ${{ matrix.function-name }} --zip-file fileb://${{ matrix.project }}.zip
