name: Deploy all

on: [workflow_dispatch]

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    timeout-minutes: 10

    steps:
      - name: Initialize
        uses: khrabrovart/articles-web/.github/workflows/initialize.yml

      - name: Build frontend
        uses: khrabrovart/articles-web/.github/workflows/build-frontend.yml
