name: Deploy all

on: [workflow_dispatch]

jobs:
  initalize:
    uses: ./.github/workflows/initialize.yml

  build-frontend:
    uses: ./.github/workflows/build-frontend.yml

  terraform:
    uses: ./.github/workflows/terraform-apply.yml
