name: Deploy frontend

on: [workflow_dispatch]

jobs:
  deploy:
    runs-on: ubuntu-latest

    timeout-minutes: 10

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Clone repository
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Cache node_modules
        env:
          cache-name: cache-node-modules
        uses: actions/cache@v3
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/yarn.lock') }}

      - name: Install dependencies
        run: yarn install

      - name: Build project
        run: yarn build

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.1.9

      - name: Initialize Terraform
        working-directory: ./infrastructure
        run: terraform init -input=false

      - name: Validate Terraform
        working-directory: ./infrastructure
        run: terraform validate -no-color

      - name: Plan Terraform
        env:
          TF_VAR_allowed_account_id: ${{ secrets.ALLOWED_ACCOUNT_ID }}
        working-directory: ./infrastructure
        run: terraform plan -input=false -no-color
