name: Destroy All

on: [workflow_dispatch]

jobs:
  plan-destroy:
    name: Plan Destroy All Resources
    runs-on: ubuntu-latest
    timeout-minutes: 2

    defaults:
      run:
        working-directory: infrastructure

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Clone repository
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.1.9

      - name: Destroy Terraform
        env:
          TF_VAR_allowed_account_id: ${{ secrets.ALLOWED_ACCOUNT_ID }}
        run: |
          terraform init -input=false
          terraform plan -destroy

  apply-destroy:
    name: Apply Destroy All Resources
    needs: plan-destroy
    runs-on: ubuntu-latest
    environment: Production
    timeout-minutes: 2

    defaults:
      run:
        working-directory: infrastructure

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Clone repository
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.1.9

      - name: Destroy Terraform
        env:
          TF_VAR_allowed_account_id: ${{ secrets.ALLOWED_ACCOUNT_ID }}
        run: |
          terraform init -input=false
          terraform apply -destroy
