name: Apply Terraform

on:
  workflow_call:

jobs:
  plan:
    env:
      TF_VAR_allowed_account_id: ${{ secrets.ALLOWED_ACCOUNT_ID }}

    runs-on: ubuntu-latest

    timeout-minutes: 10

    defaults:
      run:
        working-directory: ./infrastructure

    steps:
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.1.9

      - name: Initialize Terraform
        run: terraform init -input=false

      - name: Validate Terraform
        run: terraform validate -no-color

      - name: Plan Terraform
        run: terraform plan -input=false -no-color
