name: Apply Terraform

on: [workflow_dispatch]

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    timeout-minutes: 10

    steps:
      - name: Clone repository
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.1.9

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Initialize Terraform
        run: |
          cd infrastructure
          terraform init -input=false

      - name: Validate Terraform
        run: |
          cd infrastructure
          terraform validate -no-color

      - name: Plan Terraform
        run: |
          cd infrastructure
          terraform plan -input=false -no-color
