name: Deploy frontend

on: [workflow_dispatch]
jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    defaults:
      run:
        working-directory: ./frontend
    timeout-minutes: 10
    steps:
      - name: Clone repository
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: 12

      - name: Build project
        run: yarn run build

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::954121004694:role/GithubActionsRole
          aws-region: us-east-1

      - name: Deploy to S3
        run: aws s3 sync ./build/ s3://articles-frontend --delete